# Generated by Django 2.0.5 on 2018-10-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=64)),
                ('birthday', models.DateTimeField(blank=True, verbose_name='date of a birth')),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Webpage', max_length=64)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='webpages',
            field=models.ManyToManyField(to='hosting.Webpage'),
        ),
    ]
