# Generated by Django 2.0.5 on 2018-10-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='owner',
            new_name='user',
        ),
    ]
