# Generated by Django 2.0.5 on 2018-10-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
