# Generated by Django 2.0.5 on 2018-10-18 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosting', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='webpages',
        ),
        migrations.AddField(
            model_name='webpage',
            name='webpages',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
